export
    const
    MESSAGING_SERVICE = "MESSAGING_SERVICE",
    UNIVERSITY_SERVICE = "UNIVERSITY_SERVICE",
    USER_SERVICE = "USER_SERVICE",
    MESSAGING_SERVICE_GQL = "MESSAGING_SERVICE_GQL",
    UNIVERSITY_SERVICE_GQL = "UNIVERSITY_SERVICE_GQL",
    USER_SERVICE_GQL = "USER_SERVICE_GQL"
