name: Test/Release

on:
  push:
    branches: [release]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: install & build
        run: |
          npm i --force
          CI=false NODE_ENV=production npm run build
        env:
          NODE_ENV: production

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/

  deploy-to-lg-server:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build/

      - name: copy file via ssh key to first server
        uses: appleboy/scp-action@specific-version  # replace "specific-version" with a known version
        with:
          host: "43.204.142.210"
          username: "ec2-user"
          key: ${{ secrets.SSH_PRIVATE_KEY_FOR_RELEASE }}
          port: 22
          source: "build/*"
          target: "~/unisala-web"

      - name: ssh and setup on first server
        uses: appleboy/ssh-action@specific-version  # replace "specific-version" with a known version
        with:
          host: "43.204.142.210"
          username: "ec2-user"
          key: ${{ secrets.SSH_PRIVATE_KEY_FOR_RELEASE }}
          port: 22
          script: |
            cd unisala-web/build
            sudo rm -rf /var/www/html/* 
            sudo cp -r * /var/www/html

  deploy-to-md-t3:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build/

      - name: copy file via ssh key to second server
        uses: appleboy/scp-action@specific-version  # replace "specific-version" with a known version
        with:
          host: "35.154.130.113"
          username: "ec2-user"
          key: ${{ secrets.P_SSH_PRIVATE_KEY }}
          port: 22
          source: "build/*"
          target: "~/unisala-web"

      - name: ssh and setup on second server
        uses: appleboy/ssh-action@specific-version  # replace "specific-version" with a known version
        with:
          host: "35.154.130.113"
          username: "ec2-user"
          key: ${{ secrets.P_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd unisala-web/build
            sudo rm -rf /var/www/html/* 
            sudo cp -r * /var/www/html
