name: Prod

on:
  push:
    branches: [release]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: build
      run: |
        npm i -f
        npm run build

    - name: copy file via ssh key
      uses: appleboy/scp-action@release
      with:
        host: "35.154.130.113"
        username: "ec2-user"
        key: ${{ secrets.P_SSH_PRIVATE_KEY }}
        port: 22
        source: "build/*"
        target: "/var/www/html/"
