name: Prod

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: build
      run: |
        ls
        npm -v
        npm run build

    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: "44.204.233.28"
        username: "ec2-user"
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "build/*"
        target: "/var/www/html/"
