name: Test/Release

on:
  push:
    branches: [test, release]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name : install & build
      run: |
        npm i
        npm run build-win

    - name: copy file via ssh key
      if: ${{github.ref == 'refs/heads/test'}}
      uses: appleboy/scp-action@master
      with:
        host: "3.89.121.12"
        username: "ec2-user"
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "build/*"
        target: "~/unisala-web"
